import React from 'react'
import Head from 'next/head'
import Link from 'next/link'


export default function Header(props) {
    const title = "Zishere" + (props.title ? ` | ${props.title}` : "");
    return (
        <header className="sticky top-0 z-50">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-cyan text-2xl font-bold flex justify-end pt-4">
                <Link href="/blog">
                    <a className="mx-8">Blog</a>
                </Link>
                <Link href="/about">
                    <a >About</a>
                </Link>
            </div>
        </header>
    )
}
