import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image';
import iconImage from '../public/favicon-192x192.png';


export default function Header(props) {
    const title = "Zishere" + (props.title ? ` | ${props.title}` : "");
    return (
        <header className="">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-cyan text-2xl font-bold flex items-center justify-between p-4 bg-navy border-b-2 border-cyan">
                <Link href="/">
                    <a style={{ width: 48, height: 48}} className="border-2 border-cyan">
                        <Image  alt="zishere-icon" width={48} height={48} src={iconImage}></Image>
                    </a>
                </Link>
                <div>
                    <Link href="/blog">
                        <a className="mx-8">Blog</a>
                    </Link>
                    <Link href="/about">
                        <a >About</a>
                    </Link>
                </div>
            </div>
        </header>
    )
}
