import React from 'react'
import Head from 'next/head'

export default function Header(props) {
    console.log(props.title)
    const title = "Zishere" + (props.title ? ` | ${props.title}` : "");
    return (
        <header className="sticky top-0 z-50">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-cyan text-2xl font-bold flex justify-end pt-4">
                    <a className="mx-8" href="#">Blog</a>
                    <a href="#">About</a>
            </div>
        </header>
    )
}
